services:
  haproxy:
    image: haproxy:2.8
    container_name: haproxy
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    ports:
      - "80:80"
    links:
      - nginx
    depends_on:
      - nginx
  nginx:
    image: nginx:1.22.1
    container_name: nginx
    volumes:
      - ./php:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    expose:
      - 80
    depends_on:
      - php
      - postgres

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./php:/var/www/html
    expose:
      - 9000
    depends_on:
      - postgres

  postgres:
    image: postgres:17.1
    container_name: postgres
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: shumkin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: main
    ports:
      - "5432:5432"
