{
 "title": "HAproxy",
 "description": "HAproxy",
 "tags": [
  "haproxy",
  "backend"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,5m,1h,6h,1d" },
   { "name": "alias", "label": "Load Balancer", "query": { "query": "label_values(haproxy_up, pod)" } },
   {
    "name": "backend",
    "label": "Backend",
    "query": {
     "query": "label_values(haproxy_backend_bytes_in_total{pod=\"$alias\"}, backend)"
    }
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": {
     "query": "label_values(haproxy_backend_http_responses_total{pod=\"$alias\", backend=~\"$backend\"}, code)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Backend Responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_backend_http_responses_total{backend=~\"$backend\", code=~\"$code\"}[180s])",
     "legendFormat": "{{ backend }}/{{ code }} - NS:{{exported_namespace}} - Route:{{route}}"
    }
   ]
  },
  {
   "title": "Response Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_backend_response_errors_total{backend=~\"$backend\"}[180s])",
     "legendFormat": "{{ backend }} - NS:{{exported_namespace}} Route:{{route}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Bytes IN",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_backend_bytes_in_total{backend=~\"$backend\"}[180s])",
     "legendFormat": "{{ backend }} - NS:{{exported_namespace}} - Route:{{route}}"
    }
   ]
  },
  {
   "title": "Bytes OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_backend_bytes_out_total{backend=~\"$backend\"}[180s])",
     "legendFormat": "{{ backend }} - NS:{{exported_namespace}} - Route {{route}}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "New Connections Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_backend_connections_total{backend=~\"$backend\"}[180s])",
     "legendFormat": "{{ backend }} - NS:{{exported_namespace}} - Route:{{route}}"
    }
   ]
  },
  {
   "title": "Connection Errors Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(haproxy_backend_connection_errors_total{backend=~\"$backend\"}[180s])",
     "legendFormat": "{{ backend }} - NS:{{exported_namespace}} - Route:{{route}}"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Current Queue Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_current_queue{backend=~\"$backend\"}",
     "legendFormat": "{{ backend }} - NS:{{exported_namespace}} - Route:{{route}}"
    }
   ]
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Active Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_current_sessions{backend=~\"$backend\"}",
     "legendFormat": "{{ backend }} - NS:{{exported_namespace}} - Route:{{route}}"
    }
   ]
  },
  {
   "title": "New Session Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_current_session_rate{backend=~\"$backend\"}",
     "legendFormat": "{{ backend }} - NS:{{exported_namespace}} - Route:{{route}}"
    }
   ]
  },
  {
   "title": "Max Active Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_max_sessions{backend=~\"$backend\"}",
     "legendFormat": "{{ backend }} - NS:{{exported_namespace}} - Route:{{route}}"
    }
   ]
  },
  {
   "title": "Max Session Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "haproxy_backend_max_session_rate{backend=~\"$backend\"}",
     "legendFormat": "{{ backend }} - NS:{{exported_namespace}} - Route:{{route}}"
    }
   ]
  }
 ]
}