global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__param_target]
        target_label: instance
      - target_label: job
        replacement: 'node'

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__param_target]
        target_label: instance
      - target_label: job
        replacement: 'nginx'
